config/routes.rb
OutfitterApp::Application.routes.draw do

  root 'welcome#index'

  resources :users
  resources :outfits
  resources :comments

  get  "/session/new"  => "session#new"
  post "/session"      => "session#create"
  get  "/logout"       => "session#destroy"
  get "/all_outfits" => "outfits#index"

  get "/random" => "outfits#random"
  patch "/vote/:id" => "outfits#vote"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :outfit
  validates(:text_section, { :presence => true } )
end

app/models/outfit.rb
class Outfit < ActiveRecord::Base
  has_many :comments
  has_many :votes
  belongs_to :user
  has_attached_file :photo, :styles => { :small => "300x450>" },
                    :url  => "/assets/products/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension",
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials }
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/jpg', 'image/png']
  validates(:description,  { :presence => true } )
  validates(:brand_name,  { :presence => true } )
  validates(:style,  { :presence => true } )

  def s3_credentials
    {:bucket => "Outfitter", :access_key_id => "AKIAIL22AKTKC4BBHAZA", :secret_access_key => "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"}
  end
end

# @outfit = Outfit.new(:description => "cool")
# @outfit.save

# @outfit.liked_by @user
# @outfit.votes.size

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :outfits
  has_secure_password
  validates(:name,     { :presence     => true })
  validates(:email,    { :uniqueness   => { case_sensitive: false }})
  validates(:password, { :length       => { :minimum => 8, :maximum => 16 },
                         :presence     => true,
                         :confirmation => true }) # must enter confirmation password
  validates(:gender,  { :presence => true})
  validates(:age, {:presence => true})
  validates(:style, {:presence => true})

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def logged_in?
    current_user.present?
  end

  # declare a method as a helper
  # http://api.rubyonrails.org/classes/AbstractController/Helpers/ClassMethods.html#method-i-helper_method
  # which means we can use the methods in the view as well
  helper_method(:current_user, :logged_in?)

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


  def create
    @user = current_user
    @comment = Comment.new(comment_params)
      if @comment.save
        redirect_to("/users/#{current_user.id}")
      else
        render :new
      end
  end

  private
  def comment_params
  params.require(:comment).permit(:outfit_id, :user_id, :text_section)
  end
end

app/controllers/outfits_controller.rb
class OutfitsController < ApplicationController

  def index
    @user = current_user
    @outfits = Outfit.all.order(:created_at)
    # @likes = likes
    # @outfit = Outfit.new
  end

  def new
    @outfits = Outfit.all
    @outfit = Outfit.new
    @user = current_user
    #displays new form
  end

  def create
    @outfits = Outfit.all
    @user = current_user
    @outfit = Outfit.new(outfit_params)

      if @outfit.save
        redirect_to("/")
      else
        # render the new.html.erb file with @user
        render :new
      end
  end

  def all_outfits
    @oufits = Outfit.all
    #All outfits page linking to index
  end

  def vote
    # @user = User.find(params[:user_id])
    @outfit = Outfit.find(params[:id])
    @outfit.vote_count += 1
    @outfit.save
    redirect_to(outfits_path) #or /outfits
  end

  def random
    @instagram_outfits = outfit_search
    #Explore outfits page
  end

  def outfit_search
    results = []
    response = HTTParty.get("https://api.instagram.com/v1/tags/mensoutfits/media/recent?client_id=#{ENV['INSTAGRAM_CLIENT_ID']}")
    outfit_links = response["data"].map do |gram|
      results << [gram["images"]["low_resolution"]["url"],
      gram["likes"]["count"]]
    end
    results
  end
  #API USAGE BOY


  private

  def outfit_params
    params.require(:outfit).permit(
      :description,
      :style,
      :brand_name,
      :user_id,
      :photo
      )
  end
end

# https://api.instagram.com/oauth/authorize/?client_id=d5809c177a14434cb71f0fbb80be9d84&redirect_uri=http://intense-stream-2912.herokuapp.com/
# &response_type=code

# curl \-F 'client_id=d5809c177a14434cb71f0fbb80be9d84' \
#     -F 'client_secret=4b0d530df56f4e40ae76d95287fedbec' \
#     -F 'grant_type=authorization_code' \
#     -F 'redirect_uri=http://intense-stream-2912.herokuapp.com/' \
#     -F 'code=3eb83ef10a3044dba8f7cb4d4a5b1772' \https://api.instagram.com/oauth/access_token

#     https://api.instagram.com/oauth/authorize/?client_id=d5809c177a14434cb71f0fbb80be9d84&redirect_uri=http://intense-stream-2912.herokuapp.com/&response_type=code

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
  end

  def create
    # finds the user by the given email
    user = User.find_by(email: params[:email])
    # if we found the user and they gave us the right password
    if user && user.authenticate(params[:password])
      # store user id in session
      session[:user_id] = user.id
      redirect_to("/")
    else
      # rerender the login form
      render(:new)
    end
  end

  def destroy
    # we can set the session user_id to nil
    session[:user_id] = nil
    redirect_to(root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
    redirect_to("/")
      else
    # render the new.html.erb file with @user
    render :new
      end
  end

  def show
    @user = User.find_by(id: params[:id])
    @outfits = @user.outfits
  end
  def vote
    # @user = User.find(params[:user_id])
    @outfit = Outfit.find(params[:id])
    @outfit.vote_count += 1
    @outfit.save
    redirect_to(user_path) #or /outfits
  end

private #only for the controller 22

  def user_params
    params.require(:user).permit(:name, :gender, :email, :style, :age, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @current_user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OutfitterApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<a href="/"><span class="logo">O U T F<img class="logo_img" src="http://i62.tinypic.com/rwur9f.jpg">T T E R</span></a>




<%= yield %>

</body>
</html>

app/views/outfits/index.html.erb
 <br><a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>

<br>
<h1>All Outfits </h1>

  <% @outfits.each do |outfit| %>
    <%= image_tag outfit.photo.url(:small) %> <br>
    <strong>Description: </strong>  <%= outfit.description %> <br>
    <strong>Brand Name: </strong> <%= outfit.brand_name %> <br>
    <strong>Style: </strong><%= outfit.style %> <br>
    <strong><p class="ig_likes">♥ <%= outfit.vote_count %> likes </p></strong>
    <%= form_tag("/vote/#{outfit.id}", method: "patch") do %>
      <%= submit_tag("Like") %>
    <% end %>
  <% end %>

app/views/outfits/new.html.erb
 <br><a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>


<% @outfit.errors.messages.each do |attr, message| %>
  <p>error on <%= attr %><%= message %></p>
<% end %>

<h1> Upload An Outfit! </h1>

<%= form_for @outfit, :url => outfits_path, :html => {:multipart => true } do |f| %>
  <%= f.file_field :photo %>
  <%= f.label(:description) %>
    <%= f.text_field(:description) %>
  <%= f.label(:brand_name) %>
    <%= f.text_field(:brand_name) %>
  <%= f.label(:style) %>
    <%= f.text_field(:style) %>
    <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit %>



<% end %>

app/views/outfits/random.html.erb
 <br><a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>

<br>
<h1> Random Outfits </h1>
<a href="/random">Click for new outfits!</a>
</p>
<br>


<% @instagram_outfits.each do |outfit| %>
<div class="outfit">
   <img src="<%= outfit[0] %>"/><br>
<span class="ig_likes">♥ <%= outfit[1] %> likes </span>
</div>

<% end %>

app/views/session/new.html.erb
Login:
<p>
<ul>
    <%= form_tag("/session", method: "post") do %>
      <%= label_tag(:email) %>
      <%= text_field_tag(:email) %>
      <%= label_tag(:password) %>
      <%= password_field_tag(:password) %>
      <%= submit_tag("Login") %>
      <% end %>
<ul>

</p>

app/views/users/_new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label(:name) %>
    <%= f.text_field(:name) %>
    <br>
  <%= f.label(:email) %>
    <%= f.text_field(:email) %>
        <br>

  <%= f.label(:gender) %>
    <%= f.select(:gender, ["Male", "Female"]) %>
        <br>

  <%= f.label(:age) %>
    <%= f.number_field(:age) %>
        <br>

  <%=f.label(:style) %>
    <%= f.text_field(:style) %>
        <br>

  <%= f.label(:password) %>
    <%= f.password_field(:password) %>
        <br>

  <%= f.label(:password_confirmation) %>
    <%= f.password_field(:password_confirmation) %>
        <br>

  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
 <br><a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>

<h1> All Users </h1>

<% @users.each do |user| %>
  <a id="user_names" href="/users/<%= user.id %>"><%= user.name %></a>

  <p class="user_attributes"><strong>Name:</strong></p> <%= user.name %>
  <p class="user_attributes">Gender:</strong></p> <%= user.gender %>
  <p class="user_attributes">Email:</strong></p> <%= user.email %>
  <p class="user_attributes">Style:</strong></p> <%= user.style %>
  <p class="user_attributes">Age:</strong></p> <%= user.age %>
  <br>
  <br>

  <% end %>

app/views/users/new.html.erb
<h1> Please fill in your information below </h1>

<% @user.errors.messages.each do |attr, message| %>
  <p>error on <%= attr %><%= message %></p>
<% end %>

app/views/users/show.html.erb
 <br><a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>
<p>
<br>
<h1><%= @user.name%>'s Gallery</h1>
</p>

<!-- @outfits = [outfit_instance, outfit_instance, etc] -->


<% i=1 %>
<table>
  <tr>
<% @outfits.each do |outfit| %> <% i += 1 %>
  <td>
 <%= image_tag outfit.photo.url(:small) %>
 <br>
<strong>Style:</strong> <%= outfit.style %>
<br>
<strong>Brand:</strong> <%= outfit.brand_name %>
<br>
<strong>Description:</strong> <%= outfit.description %>
<br>
 <strong><p class="ig_likes">♥ </strong> <%= outfit.vote_count %> likes</p>
  <%= form_tag("/vote/#{outfit.id}", method: "patch") do %>
     <%= submit_tag("Like") %>
    <% end %>
    <%= form_for(Comment.new) do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.text_area :text_section %>
    <%= f.hidden_field :outfit_id, :value => outfit.id%>
    <%= f.submit 'Add Comment' %>
  <% end %>
  </td>
  <% if i.modulo(6)==5 %></tr><tr><% end %>
    <% end %>
  </table>

app/views/welcome/index.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



    <% if logged_in? %>
        <h2>Hi, <%= current_user.name %>!</h2>

          <a class="links" href="/logout"> Logout</a>
        <%= link_to("Upload an outfit", new_outfit_path, class: "links") %>

        <a class="links" href="/users/<%=current_user.id%>">View your gallery</a>

        <%= link_to("All outfits", all_outfits_path, class: "links") %>

        <a class="links" href="/random">Explore Outfits!</a>

        <a class="links" href="/users">Explore Users!</a>


        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div class="fb-like" data-href="http://intense-stream-2912.herokuapp.com/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    <% else %>
        <%= link_to("Sign up", new_user_path, class: "links") %>
        <%= link_to("Login", session_new_path, class: "links") %>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <div class="fb-like" data-href="http://intense-stream-2912.herokuapp.com/" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
    <% end %>
</p>